### ISSUE TITLE
Feature Request: Add a property to show which expansion the card is from

### ISSUE THREAD

**Issue by fikal** [HearthSim/hearthstonejson#12]

**Comment by burythehammer** [comment]
The way the JSON is structured, each card should be an element of a set which describes the expansion or adventure the card is contained within.

Here's an example of how I parsed the cards and set the card set as a property using ruby: https://github.com/burythehammer/hearthwiz/blob/master/db/helpers/card_seed_helper.rb

There is another issue which discussed flatmapping these collections as a property within each card, which you may find easier: https://github.com/Sembiance/hearthstonejson/issues/7

**Comment by jleclanche** [comment]
@fikal Isn't the card set enough for this?

**Comment by fikal** [comment]
@jleclanche Unless I have missed something, when you download all sets, there is no way to know which expansion the card came from.

**Comment by jleclanche** [comment]
I see. I'll try to add cardset in the rewrite but might be a couple weeks until I can get to it.

**Comment by Rtransat** [comment]
+1 https://github.com/HearthSim/hearthstonejson/issues/17

**Comment by jleclanche** [comment]
This has been completed in the new api

https://api.hearthstonejson.com/v1/
