### ISSUE TITLE
Impossible to fetch http://hearthstonejson.com/json/AllSets.frFR.json 

### ISSUE THREAD

**Issue by GeminiCode** [HearthSim/hearthstonejson#16]
Hi, 
I can't fetch http://hearthstonejson.com/json/AllSets.frFR.json there is a reason ?

Thanks

**Comment by jleclanche** [comment]
Hey, we're moving the DNS to a different provider and it's taking a lot longer than planned :( It should be back up this week, thanks for bearing with us.

**Comment by jleclanche** [comment]
BTW, if you need the json urgently, I can send it to you directly.

**Comment by GeminiCode** [comment]
Can I read this json and AllSets.enUS.json on a other location ?

**Comment by jleclanche** [comment]
@GeminiCode The site is back up now (may take another 15-30 minutes depending on your dns cache...)

**Comment by GeminiCode** [comment]
My error is always here :( 
ava.net.SocketTimeoutException: Timeout while fetching URL: http://hearthstonejson.com/json/AllSets.frFR.json. My bot cannot access to this file anymore :(

**Comment by jleclanche** [comment]
I'm not seeing this:

```
--2015-11-04 16:22:49--  http://hearthstonejson.com/json/AllSets.frFR.json
Resolving hearthstonejson.com (hearthstonejson.com)... 176.92.231.78
Connecting to hearthstonejson.com (hearthstonejson.com)|176.92.231.78|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 405285 (396K) [application/json]
Saving to: ‘AllSets.frFR.json’

AllSets.frFR.json                                         100%[======================================================================================================================================>] 395.79K  99.8KB/s   in 4.0s   

2015-11-04 16:22:54 (98.7 KB/s) - ‘AllSets.frFR.json’ saved [405285/405285]
```

**Comment by beheh** [comment]
Fine here. Java has a separate DNS cache though, so maybe that's the issue?

**Comment by GeminiCode** [comment]
@beheh @jleclanche My app is a Google cloud plateform app. I restarted instances , it works now . There is a DNS cache which had remained on one instance . Sorry guys .... Thanks for your help.

**Comment by jleclanche** [comment]
Cool!

**Comment by GeminiCode** [comment]
something changed since last week. The error backs today ...

**Comment by beheh** [comment]
What errors are you getting? Timeouts? I can fetch http://hearthstonejson.com/json/AllSets.frFR.json from here and from my web server without any problems.

**Comment by GeminiCode** [comment]
java.net.SocketTimeoutException: Timeout while fetching URL: http://hearthstonejson.com/json/AllSets.frFR.json
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.convertApplicationException(URLFetchServiceImpl.java:178)
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:43)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:543)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:422)
	at java.net.URL.openStream(URL.java:1055)
	at com.geminicode.hssc.utils.CardReader.read(CardReader.java:41)

Code : https://github.com/GeminiCode/Hearthstone-search/blob/master/src/main/java/com/geminicode/hssc/utils/CardReader.java

**Comment by beheh** [comment]
There might be a temporary routing issue between you and the server. http://isup.me/http://hearthstonejson.com/json/AllSets.frFR.json also tells me the site is up.

Are you caching the json file? You shouldn't really need to fetch the file too often, since patches usually happen in pretty long intervals. Maybe you could run an update service once once/twice a day which saves the file and let your application work from a local file (that way you're also more resilient against real downtimes from hearthstonejson's side).

**Comment by jleclanche** [comment]
@GeminiCode You should fetch `https://hearthstonejson.com/json/patchVersion.json` on a semi-regular interval instead. If it changes, then you fetch the bigger json files. It's really wasteful to just fetch the big one every time.

**Comment by GeminiCode** [comment]
I fetch every mondays the bigger json files. in order to prevent this problem, I will fetch a local copy of the biggen json files. I will fetch https://hearthstonejson.com/json/patchVersion.json every mondays in order to verify changes. 

@beheh @jleclanche Thanks
