### ISSUE TITLE
Provide other json output ?

### ISSUE THREAD

**Issue by Rtransat** [HearthSim/hearthstonejson#17]
Hi,

Can you provide an other output for AllSets.LANG.json file ?

For example it would be great to remove the key which contains the card set and add it to card property. (It would be more easy to fetch, otherwise I need to do a nested each)

```json
{
    "Basic":[
        {"id":"GAME_004","name":"ABS","type":"Enchantment","text":"Vos tours sont plus courts."},
        {"id":"CS2_083e","name":"Aiguisé","type":"Enchantment","text":"+1 ATQ pendant ce tour.","playerClass":"Rogue","mechanics":["OneTurnEffect"]},
        {"id":"CS2_122e","name":"Amélioration","type":"Enchantment","text":"Le chef de raid confère +1 ATQ à ce serviteur."}
    ],
    "Blackrock Mountain": [
        "...",
    ]
}
```

to

```json
[
    {"id":"GAME_004","name":"ABS","type":"Enchantment","text":"Vos tours sont plus courts.", "set": "Basic"},
    {"id":"CS2_083e","name":"Aiguisé","type":"Enchantment","text":"+1 ATQ pendant ce tour.","playerClass":"Rogue","mechanics":["OneTurnEffect"], "set": "Basic"},
    {"id":"CS2_122e","name":"Amélioration","type":"Enchantment","text":"Le chef de raid confère +1 ATQ à ce serviteur.", "set": "Basic"}
]
```

The ```set``` property has been added in the card data itself.

**Comment by jleclanche** [comment]
I have a new API coming up for next patch, it'll run side by side with the old one. I'll try to push it soon.

**Comment by Rtransat** [comment]
Glad to hear it :)

**Comment by jleclanche** [comment]
@Rtransat Here is the new API:

https://api.hearthstonejson.com/

I'm not announcing it yet. I'm open to feedback and breaking changes before I do so.

List of changes:

- API now has its own subdomain
- API is now versioned (/v1/)
- Separate output for each build. /v1/latest/ will always give you the latest build.
- Locales are now generated into their own directory
- Zip support has been removed in favour of server compression
- Cards:
  - CardSet separation has been removed as it was largely unused
  - Tags are not localized anymore (mostly this just means uppercased)
  - Created separate "collectible" set
  - Added individual "set" property
  - Added some more mechanics (forgetful, treasure...)
  - Added entourage property
  - Added playRequirements property
- Card backs:
  - Added more properties from the DBF

**Comment by Rtransat** [comment]
The data structure seems better :)
Can you provide the different "set" constant, for example what is "FP1" ?
I don't know what is entourage property, can you explain ? It seems to connected to other card but I'm not sure.

A new doc will come with this new API? :)

Thx again ;)

**Comment by jleclanche** [comment]
>  Can you provide the different "set" constant, for example what is "FP1"?
Enums are all there, copied from the game itself: 
https://github.com/HearthSim/python-hearthstone/blob/master/hearthstone/enums.py

FP1 is Naxxramas. I'd like to stick to the game's enums if at all possible... but yeah this is one of the more confusing ones. 

>  I don't know what is entourage property, can you explain ? It seems to connected to other card but I'm not sure.

Some cards that have specific, related cards instead of a filter have an entourage... it's as vague as that. Ysera, Animal Companion, ...

>  And may be, you can add a image/imageGold property to the output with the full URI?

Unfortunately the images are completely decoupled from the card data. If at some point I add image support it'd be separated from this json file. Take a look for yourself at the original extracted files: https://github.com/hearthsim/hs-data

> A new doc will come with this new API? :)

Sure. Let me know what needs documentingas a priority.

**Comment by Rtransat** [comment]
Thx for the details.

About images, I was talking about insert the URI from wow.zamimg.com directly.

The documentation need in priority the constant definition like "FP1" for naxxramas, "PE1"... and same thing for all constant. I think it's priority to understand the json file if we don't know their representation.

**Comment by jleclanche** [comment]
Let me know all constants which are unintuitive and I'll think about aliasing them.

**Comment by Rtransat** [comment]
For the moment I check the different constant but if you make a doc, the best thing is to add everything in it for the users who want use your data.

Btw, if a minion has 0 in attack, the property "attack": 0 doesn't exists. Can you fix that ?

**Comment by jleclanche** [comment]
Done.

**Comment by Rtransat** [comment]
There is a bug with mechanics.

For example:

```
    {
        "attack": 7,
        "collectible": true,
        "cost": 5,
        "flavor": "Nothing beats rock.",
        "health": 8,
        "id": "EX1_250",
        "mechanics": [
            "OVERLOAD"
        ],
        "name": "Earth Elemental",
        "playerClass": "SHAMAN",
        "rarity": "EPIC",
        "set": "EXPERT1",
        "text": "<b>Taunt</b>. <b>Overload:</b> (3)",
        "type": "MINION"
    },
    {
        "attack": 2,
        "collectible": true,
        "cost": 1,
        "flavor": "He was so excited to get season tickets to this year's Grand Tournament.  He normally doesn't get them at first and has to buy them from Ogre scalpers.",
        "health": 1,
        "id": "AT_097",
        "name": "Tournament Attendee",
        "rarity": "COMMON",
        "set": "TGT",
        "text": "<b>Taunt</b>",
        "type": "MINION"
    },
```

The first card has taunt and overload in text description but in the mechanics array it has only overload. Same thing for the second card, the text has taunt and mechanics is empty.

**Comment by jleclanche** [comment]
Fixed.

**Comment by GeminiCode** [comment]
Hi and thanks for this amazing job guys ! 
This new structure is very usefull !

But, it's already possible to check the latest version ? like : http://hearthstonejson.com/json/patchVersion.json or it's the same url ? 
thx ^^

**Comment by jleclanche** [comment]
Ah yeah. I'll add something. It's a bit harder because since I want to support multi-build, in order to be automated it'll have to get the git tag.

**Comment by jleclanche** [comment]
@GeminiCode I will be changing the `latest` endpoint to redirect 302 to the latest build, instead of symlinking it. This means you will be able to determine the build with the URL. Does that solve the issue for you?

**Comment by jleclanche** [comment]
Hey guys, heads up, the new hearthstonejson site is in staging here:

http://hearthsim.info/hearthstonejson/

This includes all the new API documentation. It'll be moved to hearthstonejson.com once it's ready.

**Comment by Rtransat** [comment]
Good job dude :).

**Comment by jleclanche** [comment]
**Important: Deprecation notice**

The legacy files have been copied over to the following URL:
https://api.hearthstonejson.com/v0/

They will *no longer be available from their old location* as of **2016-01-01**.

The old files will remain available, unchanged, from /v0/ for the foreseeable future but new builds will not be generated in the legacy format.

The new site will go live on 2016-01-01.

**Comment by jleclanche** [comment]
Data for old builds is now available!

https://api.hearthstonejson.com/v1/

I'm closing this bug. Please open new issues for suggestions and requests.
