### ISSUE TITLE
json file packages

### ISSUE THREAD

**Issue by flowdee** [HearthSim/hearthstonejson#22]
In my case I need the json files of the latest release. But with the new api / system it's really annoying opening all folders and downloading the required files.

Would be very helpful if the latest files were hosted on github where I can checkout or at least there would be some zip file containing all the latest files.

**Comment by jleclanche** [comment]
*All* the cards are in [cards.json](https://api.hearthstonejson.com/v1/latest/enUS/cards.json). No zip needed as it's server-compressed. Or do you need a zip of all the languages as well?

If you need lower-level access, there is the hs-data repository. HearthstoneJSON is generated from there.

https://github.com/hearthsim/hs-data

**Comment by flowdee** [comment]
I need the cards.jsons from multiple languages. That's why I have to navigate through all folders which is annoying. Before the new api the languages were listed and you could simply click on the files and they were downloaded.

**Comment by jleclanche** [comment]
I'll add an `all` language with the files merged.

**Comment by flowdee** [comment]
For me personally not helpful because I need specific ones and have to exclude the other ones. Simply the opportunity to download all existing folders (with content) or here with github would be nice.

**Comment by jleclanche** [comment]
Why do you have to exclude anything? There's `cards.json` for all cards, and `cards.collectible.json` for just the collectible set. I only left those two because nobody was downloading the other ones.

I'm not sure what you actually want. If you want to work at a lower level, see the hs-data repo I linked above - it's a different format however.

**Comment by flowdee** [comment]
I only need the cards.json from DE, IT, ES, EN, RU and not the other languages. I thought you want to combine ALL languages into a large cards.json file which would be bad for me. Maybe I got you wrong.

**Comment by jleclanche** [comment]
I do intend to combine all languages in one file.

I'm not sure I understand your issue though. If you need 4 specific languages then you'll have to download 4 specific files. The URLs are predictable, that's the point of the API. So the 5 files you want will always be at these URLs:

https://api.hearthstonejson.com/v1/latest/enUS/cards.json
https://api.hearthstonejson.com/v1/latest/deDE/cards.json
https://api.hearthstonejson.com/v1/latest/itIT/cards.json
https://api.hearthstonejson.com/v1/latest/esES/cards.json
https://api.hearthstonejson.com/v1/latest/ruRU/cards.json

**Comment by flowdee** [comment]
Currently im downloading and including them. I might switch over to fetch them directly from your new api. thanks so far

**Comment by jleclanche** [comment]
Merged locales are now available here:

https://api.hearthstonejson.com/v1/latest/all/
