### ISSUE TITLE
Arcane Dust / Crafting Costs

### ISSUE THREAD

**Issue by flowdee** [HearthSim/hearthstonejson#23]
Would it be possible to include the Arcane Dust / Crafting Costs of each card?

If it's not provided it would be possible to calculate the easily.

**Comment by jleclanche** [comment]
It should be straightforward to calculate. I could add them yeah.

**Comment by flowdee** [comment]
Yep it's easy to calculate and would be amazing if it will be delivered by the api :+1:

**Comment by jleclanche** [comment]
I have added the `dust` property which is a list of crafting cost, golden crafting cost, disenchant cost, golden disenchant cost.

**Comment by flowdee** [comment]
awesome thanks @jleclanche !
