### ISSUE TITLE
Ogre Brute and Ogre Ninja do not have FORGETFUL mechanic in cards.json

### ISSUE THREAD

**Issue by Brucbbro** [HearthSim/hearthstonejson#26]
These cards, along with "Mogor the Ogre" and "Ogre Warmaul", lack the FORGETFUL mechanic listed, but for the last 2 it might be intended.

**Comment by jleclanche** [comment]
Yeah, that's Blizzard's fault - they just don't list it on there. Kind of
unfortunate.
