### ISSUE TITLE
issue with api.hearthstonejson.com

### ISSUE THREAD

**Issue by magicjin** [HearthSim/hearthstonejson#27]
i'm trying to download the json with wget, for example:
**wget --no-check-certificate https://api.hearthstonejson.com/v1/latest/zhCN/cards.json**

but it is failed and the error message is "Unable to establish SSL connection", can you take a look at this, it is fine if i download file from browser, but it is failed with wget or python requests library.

i submit the issue here because i didn't find a email at the website, sorry for the confusion.

**Comment by jleclanche** [comment]
This is the correct place to report such issues, no worries.

It sounds like your version of wget is too old. You shouldn't be using `--no-check-certificate`, FWIW. 

wget 1.17 downloads it just fine.
```
$ wget --version
GNU Wget 1.17.1 built on linux-gnu.
```

If you're on an old OS, I recommend upgrading to a newer version. Debian Jessie and Ubuntu 16.04 LTS both have a recent enough version of wget.
