### ISSUE TITLE
Standard/Wild format

### ISSUE THREAD

**Issue by vayzor** [HearthSim/hearthstonejson#31]
Hello,

Is there a way to extract the card format (Standard/Wild) as well from the game data?
Thank you

**Comment by jleclanche** [comment]
Hey!

You should be looking at the [`CardSet`](https://github.com/HearthSim/python-hearthstone/blob/master/hearthstone/enums.py#L383-L423) property. 

The Standard card sets are:

* `CORE`
* `EXPERT1`
* `BRM`
* `TGT`
* `LOE`
* `OG`

**Comment by dbrudner** [comment]
I realize this issue is 2+ years old, but I think the game has changed a ton in that time. At this point, it might be easier to include format with the cardData, or maybe provide an endpoint just to retrieve which CardSets are currently standard?
