### ISSUE TITLE
Overload doesn't appear as a mechanic in 13807's mechanics list.

### ISSUE THREAD

**Issue by peixian** [HearthSim/HearthstoneJSON#35]
The issue from https://github.com/HearthSim/HearthstoneJSON/issues/10 is back, the enUS in version 13807's cards.collectible.json and cards.json both don't have Overload listed as a mechanic. 

On further inspection, there's a lack of listing for mechanics that take a numerical value, like Spell Damage.

**Comment by jleclanche** [comment]
This should have been fixed a while ago. 13807 was generated differently than the other builds, but now it's been fixed.
