### ISSUE TITLE
Weird Imp Master texture

### ISSUE THREAD

**Issue by azeier** [HearthSim/HearthstoneJSON#37]
https://art.hearthstonejson.com/v1/256x/EX1_597.jpg
![image](https://cloud.githubusercontent.com/assets/235410/19190715/c00776aa-8ca7-11e6-8044-7b22d62b97a5.png)

**Comment by jleclanche** [comment]
Fixed in HearthSim/UnityPack@32eecf1006327ddba44c031ae85cddc0366d92f4
