### ISSUE TITLE
Figure out what the hell happened with CORS rules on S3

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HearthstoneJSON#38]
CC @amw2104 
S3 wasn't sending CORS rules for `https://api.hearthstonejson.com/v1/14830/enUS/cards.json`. I went into the bucket configuration and the CORS configuration was there as expected:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>0</MaxAgeSeconds>
    </CORSRule>
</CORSConfiguration>
```

No idea what happened but this broke silently. We need to test it out again as soon as possible, make sure it doesn't happen again.

**Comment by jleclanche** [comment]
Deleting and re-creating the CORS config fixed it, by the way.

**Comment by beheh** [comment]
We could write a runner that alerts us whenever CORS isn't available. We should be able to run it via Telegraf every hour or so, send the result to Influx and then have the usual Kapacitor ruleset to alert us (Alarmobot/Mail...) whenever it's broken.

**Comment by jleclanche** [comment]
k I'm closing this, it never happened again.
