### ISSUE TITLE
Beneath the grounds tile is all black

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HearthstoneJSON#39]
Reproduce with `./generate_card_textures.py Hearthstone/Data/Win/card*.unity3d --outdir=out --only=AT_035`

@andburn I remember you mentioned a possible fix. What was it?

**Comment by andburn** [comment]
Its because the original texture is 512x256 for some reason, and the tile code expects a square image. The fix was to either check the size before making the tile, or create the tiles from the x512 thumbs.

**Comment by jleclanche** [comment]
How does Hearthstone handle it? It has a correct tile texture.

**Comment by azeier** [comment]
Any news on this?
