### ISSUE TITLE
'No window object present' in browser-less node

### ISSUE THREAD

**Issue by tinnvec** [HearthSim/HearthstoneJSON#42]
When using the package in a server role, node doesn't have a 'window' object, which is used for the XMLHttpRequests the package makes.

One can use https://github.com/rstacruz/jsdom-global as a way of providing a window object as a stop-gap, but removing reliance on the window object or adding checks for window vs global would be the most robust route to go, I think.

**Comment by tinnvec** [comment]
Apologies, I hit submit before realizing I was on the base repo and not the npm package repo, posted to there and closing here

**Comment by jleclanche** [comment]
I see you already filed it in HearthSim/npm-hearthstonejson#2
