### ISSUE TITLE
The charset is not specified

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/HearthstoneJSON#43]
In Firefox, there are 'Â' characters being displayed. This might be fixed by setting the correct charset.

See https://github.com/HearthSim/hs-bugs/issues/651 for more details.

aws/aws-cli#1346

**Comment by jleclanche** [comment]
Something's off. The JSON spec mandates Unicode, with UTF-8 being the default.

> JSON text SHALL be encoded in Unicode. The default encoding is UTF-8.

So this is a Firefox bug.

**Comment by jleclanche** [comment]
Closing, this is a non-issue most likely to do with Firefox. It won't change anything when it comes to users of the API.
