### ISSUE TITLE
Instructions incomplete

### ISSUE THREAD

**Issue by malakai97** [HearthSim/HearthstoneJSON#44]
bootstrap.sh is not in this repo, so that should be updated

documentation on generate_card_textures.py is quite incomplete

> [16:53] <@jleclanche> malakai: pass it card*.unity3d
[16:53] <@jleclanche> from your hearthstone directory
[16:54] <@jleclanche> card*.unity3d being cardxml0.unity3d, cardtextures0, 1, 2 .unity3d etc

I may have some time to make a PR for this, but for now I wanted to document the issue.

**Comment by luoapp** [comment]
bootstrap.sh seems not needed. Was able to make it work after solving the charset issue.

**Comment by mersadk** [comment]
What is command to run **generate_card_textures.py** on Windows?

I've tried with 
`python generate_card_textures.py "C:\Program Files (x86)\Hearthstone\Data\Win\card*.unity3d" --outdir=out` 
but I get error 
`OSError: [Errno 22] Invalid argument: 'C:\\Program Files (x86)\\Hearthstone\\Data\\Win\\card*.unity3d'`

If I run
`python generate_card_textures.py "C:\Program Files (x86)\Hearthstone\Data\Win\cards0.unity3d" --outdir=out`
I get a lot of errors like
`Parsing 'AT_001' ('final/assets/game/cards/09 at/at_001/hs5-033_d.psd')
Path 'final/assets/game/cards/09 at/at_001/hs5-033_d.psd' not found for 'AT_001'`

**Comment by jleclanche** [comment]
You need to give it cardxml0.unity3d as well

**Comment by mersadk** [comment]
And all cardtextures files.

Command I used was
`python generate_card_textures.py "C:\Program Files (x86)\Hearthstone\Data\Win\cards0.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardxml0.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures0.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures1.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures2.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures3.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures4.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures5.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures6.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures7.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures8.unity3d" "C:\Program Files (x86)\Hearthstone\Data\Win\cardtextures9.unity3d" --outdir="C:\Users\mersa\Desktop\HearthstoneJSON-master\out"`

**Comment by Otsoko** [comment]
I performed successfully the code thanks to @mersadk example, but I realized that this generates the minions-spells-weapons images inside the cards, but does not generate the card image itself.

What is the step I am missing to accomplish this?

As example:

I got this: 
![ex1_116](https://cloud.githubusercontent.com/assets/2643640/25913716/057397ce-35bc-11e7-8496-e9ed096618ef.png)

I want this:
![leeroy](https://art.hearthstonejson.com/v1/render/latest/enUS/256x/EX1_116.png)

**Comment by jleclanche** [comment]
That's in https://github.com/HearthSim/Sunwell.
