### ISSUE TITLE
Always get 403 (Forbidden) when fetching cards.json with Java

### ISSUE THREAD

**Issue by kanjielu** [HearthSim/HearthstoneJSON#51]
I'm trying to fetch cards.json with Java and SpringBoot but get 403. Anyone met the same issue?
However, when I change the url to "https://api.github.com", I get 200 (OK).

```java
 //configuration
 @Configuration
 public class HttpRestConfig {
     @Bean
     public RestTemplate restTemplate(RestTemplateBuilder builder) {
         return builder.build();
     }
 }
```
```java
 //fetching code
 ResponseEntity<Object> responseEntity
                     = restTemplate.exchange("https://api.hearthstonejson.com/v1/19776/enUS/cards.json",
                     HttpMethod.GET,
                     null,
                     new ParameterizedTypeReference<Object>() {
             });
```

**Comment by jleclanche** [comment]
Check your https configuration, make sure it supports TLS 1.2. You wouldn't get a 403 but that's the only thing I can think of... curl works fine.

**Comment by kanjielu** [comment]
I'm testing on Windows 10, where TLS 1.2 is enabled by default. I'm able to fetch the result by Postman on the same machine.

**Comment by jleclanche** [comment]
Hm, come to think of it, maybe your client is just being intercepted and blacklisted by cloudflare.

Try setting a User-Agent.

**Comment by kanjielu** [comment]
I believe it's due to the Java code to fetch data. I'm closing the issue.

**Comment by jmmk** [comment]
Just ran into this (403 Forbidden response) and I can confirm that setting a `User-Agent` header solves it
