### ISSUE TITLE
Psychic Scream art is incorrect (Looks like Dragon's Fury)

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/HearthstoneJSON#55]
`LOOT_008`

**Comment by beheh** [comment]
`KAR_004a` (should be Cat in a Hat)

**Comment by jleclanche** [comment]
Looks like The Coin is also affected (`GAME_005`).

**Comment by jleclanche** [comment]
@andburn do you have any idea what's going on?

**Comment by beheh** [comment]
We think this is an issue with extracting the assets from the game files.

**Comment by andburn** [comment]
It happened with *Cat in a Hat* [previously](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3097), the Coin too I think. I'm not sure what the solution was, if there even was one.

If I run the script locally, either all cards or only one, the results for the above are all the correct art. Could it be somewhere else in the pipeline or a legacy storage thing?

**Comment by jleclanche** [comment]
All fixed, cleaned up and rerendered (cache should update soon).

**Comment by riQQ** [comment]
`Elemental Destruction`'s card art is currently wrong (uses `Crackle`'s art)
