### ISSUE TITLE
Fix missing set for Hall of Fame cards

### ISSUE THREAD

**Issue by beheh** [HearthSim/HearthstoneJSON#60]
- Ice Block has `"set":"HOF"` on the enchantment instead
- Coldlight Oracle is completely missing it
- Molten Giant is completely missing it

**Comment by haubix** [comment]
I can verify that the following cards need to be checked:

- Coldlight Oracle (EX1_050)
- Ice Block (EX1_295)
- Molten Giant (EX1_620)

**Comment by jleclanche** [comment]
Fixed.
