### ISSUE TITLE
cards.collectible.json 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Jonius7** [HearthSim/HearthstoneJSON#62]
I've been trying to use cards.collectible.json using a Javascript AJAX request but it keeps coming up with the Access-Control-Allow-Origin issue in Chrome.
I notice from past threads that cards.json had this issue, so I tried that and it worked. Just thought I'd put that out there, perhaps have the same configuration for cards.collectible.json that cards.json has as well?

**Comment by jleclanche** [comment]
Try clearing your cache. They have the same config.

**Comment by Jonius7** [comment]
Thanks, that worked. Thought clearing some cookies would work, forgot about the cache.
