### ISSUE TITLE
Artist Name Inconsistencies

### ISSUE THREAD

**Issue by mhaubenwallner** [HearthSim/HearthstoneJSON#70]
Hi there!
First of all thanks for providing this awesome service - I'm using it on my Hearthstone quiz site called [MemorizeHS](https://memorizehs.com/).

In the statistics pages of my site, I'm outputting some card information, including artists. There I found some typos/name inconsistencies in your JSON data.
For example [here](https://memorizehs.com/statistics/card/OG_173) and [here](https://memorizehs.com/statistics/card/BOT_101) should be the same artist.

I've compiled a list for you for easy search and replace:

A. J. Nazzaro / A.J. Nazzaro
Alex Aleksandrov / Alex Alexandrov / Alexander Alexandrov
Anton Kagoukin / Anton Kagounkin
Anton Magdalin / Anton Magdalina
Arthur Gimaldinov / Arthur Gimalinov
Ben Zhang / Benjamin Zhang
Craig Elliot / Craig Elliott
Dan Orizio / Dany Orizio
E. M. Gist / E.M. Gist / Erik Gist (maybe?)
Eva Widermann / Eva Wilderman / Eva Wildermann
Evgeniy Zagumennyy / Evgeniy Zaqumyenny
Jakub Kasber / Jakub Kasper
Jesper Ejsing / Jesper Esjing
Kan Liu / Kan Lui
Kevin Chen / Kevin Chin (maybe?)
Konstanin Turovec / Konstantin Turovec
Laurel Austin / Laurel D. Austin
Marcelo Vignali / Marcleo Vignali
Mauricio Herrera / Maurico Herrera
Max Greck / Max Grecke
Mike Saas / Mike Sass
Milivoj Ceran / Milvoj Ceran
Phroi Gardner / Phroilan Gardner
Ralph Horsely / Ralph Horsley
Sam Nielsen / Sam Nielson
Samwise / Samwise Didier
Sean O'Danield / Sean O'Daniels / Sean O’Daniels (check single quote!)
Tyler West Studio / Tyler West Studios
Ursula dorada (last name uppercase)
Zero / Zero Yue
Zoltan Boros / Zolton Boros

Thanks again for your service!

Kind regards,
Mario

**Comment by jleclanche** [comment]
Thanks for the report. These names are directly from the game files though, so there's likely the same issue in-game.

There's nothing that can be done on the project's side, but I'm going to try to forward this to Blizzard.

**Comment by mhaubenwallner** [comment]
That was fast 👍 
Thanks for your effort nonetheless!
