### ISSUE TITLE
Card Changes - Balance Update October 2018

### ISSUE THREAD

**Issue by mhaubenwallner** [HearthSim/HearthstoneJSON#71]
Hey, just wanted to let you know that the [Balance Update October 2018](https://playhearthstone.com/en-us/blog/22549775/upcoming-balance-update-october-2018) went live globally.

These are the changes:
Giggling Inventor – Will cost 7 mana. (Up from 5)
Mana Wyrm – Will cost 2 mana. (Up from 1)
Aviana – Will cost 10 mana. (Up from 9)

Cheers

**Comment by azeier** [comment]
Everything has already been updated :+1:.
